/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg540project;

/**
 *
 * @author Goutham
 */
public class conferencesAndStudyRoomsForm extends javax.swing.JFrame {

    /**
     * Creates new form conferencesAndStudyRoomsForm
     */
    public conferencesAndStudyRoomsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomTypeGroup = new javax.swing.ButtonGroup();
        libraryGroup = new javax.swing.ButtonGroup();
        conferenceOrStudyRoomFinderLabel = new javax.swing.JLabel();
        startingDateAndTimeLabel = new javax.swing.JLabel();
        endDateAndTimeLabel = new javax.swing.JLabel();
        occupantsLabel = new javax.swing.JLabel();
        roomTypeLabel = new javax.swing.JLabel();
        libraryLabel = new javax.swing.JLabel();
        startingDateAndTimeTextField = new javax.swing.JTextField();
        endDateAndTimeTextField = new javax.swing.JTextField();
        occupancyTextField = new javax.swing.JTextField();
        studyRoomButton = new javax.swing.JRadioButton();
        conferenceRoomButton = new javax.swing.JRadioButton();
        dhHillButton = new javax.swing.JRadioButton();
        jbHuntButton = new javax.swing.JRadioButton();
        findRoomsButton = new javax.swing.JButton();
        availableRoomsLabel = new javax.swing.JLabel();
        availableRoomsPane = new javax.swing.JScrollPane();
        availableRoomsList = new javax.swing.JList();
        roomDetailsLabel = new javax.swing.JLabel();
        roomDetailsPane = new javax.swing.JScrollPane();
        roomDetailsTextArea = new javax.swing.JTextArea();
        reserveRoomButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        conferenceOrStudyRoomFinderLabel.setText("Coneference/Study Room Finder");

        startingDateAndTimeLabel.setText("Starting Date/Time:");

        endDateAndTimeLabel.setText("End Date/Time:");

        occupantsLabel.setText("Occupants:");

        roomTypeLabel.setText("Room Type:");

        libraryLabel.setText("Library:");

        roomTypeGroup.add(studyRoomButton);
        studyRoomButton.setText("Study Room");

        roomTypeGroup.add(conferenceRoomButton);
        conferenceRoomButton.setText("Conference Room");

        libraryGroup.add(dhHillButton);
        dhHillButton.setText("D.H. Hill");
        dhHillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dhHillButtonActionPerformed(evt);
            }
        });

        libraryGroup.add(jbHuntButton);
        jbHuntButton.setText("J.B. Hunt");

        findRoomsButton.setText("Find Rooms");
        findRoomsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findRoomsButtonActionPerformed(evt);
            }
        });

        availableRoomsLabel.setText("Available Rooms");

        availableRoomsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        availableRoomsPane.setViewportView(availableRoomsList);

        roomDetailsLabel.setText("Room Details");

        roomDetailsTextArea.setEditable(false);
        roomDetailsTextArea.setColumns(20);
        roomDetailsTextArea.setRows(5);
        roomDetailsPane.setViewportView(roomDetailsTextArea);

        reserveRoomButton.setText("Reserve Room");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(conferenceOrStudyRoomFinderLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(occupantsLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(occupancyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(endDateAndTimeLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(endDateAndTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(startingDateAndTimeLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(startingDateAndTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(findRoomsButton)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(libraryLabel)
                                                        .addGap(67, 67, 67)
                                                        .addComponent(dhHillButton)))
                                                .addGap(58, 58, 58))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(roomTypeLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(studyRoomButton)
                                                .addGap(40, 40, 40)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(conferenceRoomButton)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(roomDetailsLabel)
                                                .addComponent(jbHuntButton))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(availableRoomsLabel)))
                        .addGap(0, 116, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(reserveRoomButton)
                            .addComponent(availableRoomsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(roomDetailsPane))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(backButton)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(conferenceOrStudyRoomFinderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startingDateAndTimeLabel)
                    .addComponent(startingDateAndTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endDateAndTimeLabel)
                    .addComponent(endDateAndTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(occupantsLabel)
                    .addComponent(occupancyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomTypeLabel)
                    .addComponent(studyRoomButton)
                    .addComponent(conferenceRoomButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libraryLabel)
                    .addComponent(dhHillButton)
                    .addComponent(jbHuntButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(findRoomsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availableRoomsLabel)
                    .addComponent(roomDetailsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roomDetailsPane)
                    .addComponent(availableRoomsPane, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reserveRoomButton)
                    .addComponent(backButton))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dhHillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dhHillButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dhHillButtonActionPerformed

    private void findRoomsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findRoomsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findRoomsButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.hide();
        new resourcesForm().show();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conferencesAndStudyRoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conferencesAndStudyRoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conferencesAndStudyRoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conferencesAndStudyRoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conferencesAndStudyRoomsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availableRoomsLabel;
    private javax.swing.JList availableRoomsList;
    private javax.swing.JScrollPane availableRoomsPane;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel conferenceOrStudyRoomFinderLabel;
    private javax.swing.JRadioButton conferenceRoomButton;
    private javax.swing.JRadioButton dhHillButton;
    private javax.swing.JLabel endDateAndTimeLabel;
    private javax.swing.JTextField endDateAndTimeTextField;
    private javax.swing.JButton findRoomsButton;
    private javax.swing.JRadioButton jbHuntButton;
    private javax.swing.ButtonGroup libraryGroup;
    private javax.swing.JLabel libraryLabel;
    private javax.swing.JTextField occupancyTextField;
    private javax.swing.JLabel occupantsLabel;
    private javax.swing.JButton reserveRoomButton;
    private javax.swing.JLabel roomDetailsLabel;
    private javax.swing.JScrollPane roomDetailsPane;
    private javax.swing.JTextArea roomDetailsTextArea;
    private javax.swing.ButtonGroup roomTypeGroup;
    private javax.swing.JLabel roomTypeLabel;
    private javax.swing.JLabel startingDateAndTimeLabel;
    private javax.swing.JTextField startingDateAndTimeTextField;
    private javax.swing.JRadioButton studyRoomButton;
    // End of variables declaration//GEN-END:variables
}
