/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg540project;

/**
 *
 * @author Goutham
 */
public class homePageForm extends javax.swing.JFrame {

    /**
     * Creates new form studentHomePageForm
     */
    public homePageForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patronHomePageLabel = new javax.swing.JLabel();
        profileButton = new javax.swing.JButton();
        resourcesButton = new javax.swing.JButton();
        checkedOutResourcesButton = new javax.swing.JButton();
        resourceRequestsButton = new javax.swing.JButton();
        notificationsButton = new javax.swing.JButton();
        dueBalanceButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        patronHomePageLabel.setText("Patron Home Page");

        profileButton.setText("Profile");
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        resourcesButton.setText("Resources");
        resourcesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourcesButtonActionPerformed(evt);
            }
        });

        checkedOutResourcesButton.setText("Checked Out Resources");
        checkedOutResourcesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkedOutResourcesButtonActionPerformed(evt);
            }
        });

        resourceRequestsButton.setText("Resource Requests");
        resourceRequestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourceRequestsButtonActionPerformed(evt);
            }
        });

        notificationsButton.setText("Notifications");
        notificationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationsButtonActionPerformed(evt);
            }
        });

        dueBalanceButton.setText("Due Balance");
        dueBalanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dueBalanceButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutButton)
                    .addComponent(resourcesButton)
                    .addComponent(dueBalanceButton)
                    .addComponent(notificationsButton)
                    .addComponent(resourceRequestsButton)
                    .addComponent(checkedOutResourcesButton)
                    .addComponent(profileButton)
                    .addComponent(patronHomePageLabel))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patronHomePageLabel)
                .addGap(18, 18, 18)
                .addComponent(profileButton)
                .addGap(15, 15, 15)
                .addComponent(resourcesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkedOutResourcesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resourceRequestsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(notificationsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dueBalanceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutButton)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        this.hide();
        // if student, call this
        // new studentProfileForm().show();
        // if faculty, call this
        new facultyProfileForm().show();
    }//GEN-LAST:event_profileButtonActionPerformed

    private void resourcesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourcesButtonActionPerformed
       this.hide();
       new resourcesForm().show();
    }//GEN-LAST:event_resourcesButtonActionPerformed

    private void checkedOutResourcesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkedOutResourcesButtonActionPerformed
        this.hide();
        new checkedOutResourcesForm().show();
    }//GEN-LAST:event_checkedOutResourcesButtonActionPerformed

    private void resourceRequestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourceRequestsButtonActionPerformed
        this.hide();
        new resourceRequestForm().show();
    }//GEN-LAST:event_resourceRequestsButtonActionPerformed

    private void notificationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationsButtonActionPerformed
        this.hide();
        new notificationsForm().show();
    }//GEN-LAST:event_notificationsButtonActionPerformed

    private void dueBalanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dueBalanceButtonActionPerformed
        this.hide();
        new dueBalanceForm().show();
    }//GEN-LAST:event_dueBalanceButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.hide();
        new loginForm().show();
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homePageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homePageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homePageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homePageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homePageForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkedOutResourcesButton;
    private javax.swing.JButton dueBalanceButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton notificationsButton;
    private javax.swing.JLabel patronHomePageLabel;
    private javax.swing.JButton profileButton;
    private javax.swing.JButton resourceRequestsButton;
    private javax.swing.JButton resourcesButton;
    // End of variables declaration//GEN-END:variables
}
