/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg540project;

/**
 *
 * @author Goutham
 */
public class resourcesForm extends javax.swing.JFrame {

    /**
     * Creates new form resourcesForm
     */
    public resourcesForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        libraryResourcesLabel = new javax.swing.JLabel();
        publicationsButton = new javax.swing.JButton();
        conferencesAndStudyRoomsButton = new javax.swing.JButton();
        camerasButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        libraryResourcesLabel.setText("Library Resources");

        publicationsButton.setText("Publications");
        publicationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publicationsButtonActionPerformed(evt);
            }
        });

        conferencesAndStudyRoomsButton.setText("Conferences/Study Rooms");
        conferencesAndStudyRoomsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conferencesAndStudyRoomsButtonActionPerformed(evt);
            }
        });

        camerasButton.setText("Cameras");
        camerasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camerasButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton)
                    .addComponent(camerasButton)
                    .addComponent(conferencesAndStudyRoomsButton)
                    .addComponent(publicationsButton)
                    .addComponent(libraryResourcesLabel))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(libraryResourcesLabel)
                .addGap(58, 58, 58)
                .addComponent(publicationsButton)
                .addGap(18, 18, 18)
                .addComponent(conferencesAndStudyRoomsButton)
                .addGap(18, 18, 18)
                .addComponent(camerasButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backButton)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void publicationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publicationsButtonActionPerformed
        this.hide();
        new publicationsForm().show();
    }//GEN-LAST:event_publicationsButtonActionPerformed

    private void conferencesAndStudyRoomsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conferencesAndStudyRoomsButtonActionPerformed
        this.hide();
        new conferencesAndStudyRoomsForm().show();
    }//GEN-LAST:event_conferencesAndStudyRoomsButtonActionPerformed

    private void camerasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camerasButtonActionPerformed
        this.hide();
        new camerasForm().show();
    }//GEN-LAST:event_camerasButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.hide();
        new homePageForm().show();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resourcesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resourcesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resourcesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resourcesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resourcesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton camerasButton;
    private javax.swing.JButton conferencesAndStudyRoomsButton;
    private javax.swing.JLabel libraryResourcesLabel;
    private javax.swing.JButton publicationsButton;
    // End of variables declaration//GEN-END:variables
}
